spring.application.name=vigilapp

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:${POSTGRES_PORT:5432}}/${DB_NAME:${POSTGRES_DB:vigilapp_db}}
spring.datasource.username=${DB_USER:${POSTGRES_USER:postgres}}
spring.datasource.password=${DB_PASSWORD:${POSTGRES_PASSWORD:postgres}}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.thymeleaf.check-template-location=false
server.port=${PORT:${SPRING_PORT:8080}}
spring.jpa.show-sql=true

